# Generated by Django 3.0.8 on 2021-05-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era', models.CharField(help_text='What release, time or situation do these photos relate to?', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(help_text='E.g. LSFTEOTW', max_length=12)),
                ('cover_image', models.ImageField(upload_to='cover_art')),
                ('spotify_link', models.URLField()),
                ('priority', models.IntegerField(blank=True, help_text='Lower numbers appear more prominently.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('youtube_link', models.URLField()),
                ('priority', models.IntegerField(blank=True, help_text='Lower numbers appear more prominently.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(help_text='Short description of picture', max_length=50)),
                ('picture', models.ImageField(upload_to='press_pics')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='jh_site.Reel')),
            ],
        ),
    ]
