# Generated by Django 3.0.8 on 2021-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date', 'headline']},
        ),
        migrations.AlterModelOptions(
            name='reel',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['release_date', 'title']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['priority', 'title']},
        ),
        migrations.RemoveField(
            model_name='release',
            name='priority',
        ),
        migrations.AddField(
            model_name='reel',
            name='year',
            field=models.IntegerField(blank=True, help_text='More recent year appears more prominently.', null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
