# Generated by Django 3.2.3 on 2021-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh_site', '0002_auto_20210522_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Compressed version of this image', null=True, upload_to='press_pics/thumb'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='press_pics/fullsize'),
        ),
    ]
