# Generated by Django 3.2.3 on 2021-05-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jh_site', '0003_auto_20210523_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', 'headline'], 'verbose_name_plural': 'news items'},
        ),
        migrations.AlterModelOptions(
            name='release',
            options={'ordering': ['-release_date', 'title']},
        ),
    ]
