# Generated by Django 3.2.3 on 2021-05-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jh_site', '0004_auto_20210526_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='lazy',
            field=models.FileField(blank=True, help_text='Super small SVG for lazy loads', null=True, upload_to='press_pics/pixels'),
        ),
    ]
